[package]
name = "bricks"
version = "0.1.0"
authors = ["Paultheneko <tygrysekpawelpiotr1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.2"
fixedstep = "0.3"
palette = "0.5"